version: '3'
services:
  gateway:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./src/:/app/
      - ~/.aws:/root/.aws # If not provide AWS credentials from .env, just load your local AWS credentails
    command: ["uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
    env_file:
    - .env
    environment:
    - DEBUG=true
    - AWS_REGION=us-east-1
    - AWS_PROFILE=account-b-us