apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: br-gw-demo
  region: us-west-2
  version: "1.29"

iam:
  withOIDC: true
  # serviceAccounts:
  # - metadata:
  #     name: aws-load-balancer-controller
  #     namespace: kube-system
  #   wellKnownPolicies:
  #     awsLoadBalancerController: true
  podIdentityAssociations:
  - namespace: kube-system
    serviceAccountName: aws-load-balancer-controller
    wellKnownPolicies:
      awsLoadBalancerController: true
  - namespace: bedrock-proxy-api
    serviceAccountName: bedrock-proxy-api
    permissionPolicyARNs:
    - arn:aws:iam::aws:policy/AmazonBedrockFullAccess



vpc:
  clusterEndpoints:
    publicAccess: true
    privateAccess: true

addonsConfig:
  autoApplyPodIdentityAssociations: true

addons:
- name: vpc-cni
  version: latest
- name: coredns
  version: latest
- name: kube-proxy
  version: latest
- name: eks-pod-identity-agent
  version: latest


managedNodeGroups:
- name: mng-1
  privateNetworking: true
  desiredCapacity: 2
  volumeType: gp3
  spot: true
  volumeSize: 80
